### ISSUE TITLE
phpmyadmin not working

### ISSUE THREAD

**Issue by oldlastman** [nurelm/prestashop_vagrant#7]
new version of apache2 use conf-available and conf-enabled directories for config

i run:

sudo cp /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin 
sudo service apache2 reload

and now phpmyadmin it's working

may be it's necesary change provision script: replace
sudo cp /etc/phpmyadmin/apache.conf /etc/apache2/conf.d/phpmyadmin.conf
and insert
sudo cp /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin 
sudo service apache2 reload

**Comment by ppnelles** [comment]
Had the same issue,
Thanks for sharing :)

**Comment by shaabans** [comment]
Thanks for the feedback and the fix. I just noticed the first message, made the update, tested, and pushed it.
